// DontStarveInjector.idl : IDL source for DontStarveInjector
//

// This file will be processed by the MIDL tool to
// produce the type library (DontStarveInjector.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,
	helpstring("IComponentRegistrar Interface"),
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	uuid(72D7229B-C34D-439F-8190-25371D155288),
	version(1.0),
	helpstring("DontStarveInjector 1.0 Type Library"),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{8438D191-CFB0-46CC-B682-CDAA6C556271}")
]
library DontStarveInjectorLib
{
	importlib("stdole2.tlb");

	[
		uuid(8438D191-CFB0-46CC-B682-CDAA6C556271),
		helpstring("ComponentRegistrar Class")
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
};
