libpreload:
	gcc -m32 -fPIC -shared -O2 -std=c++11 -lstdc++ main.cpp -o libpreload.so
	cp libpreload.so "/home/resampler/.steam/steam/steamapps/common/Don't Starve Together Dedicated Server/bin/lib32/"